version: 2

models:
  - name: bronze_tpch_orders
    columns:
      - name: order_id
        data_tests:
          - unique
          - not_null
      - name: customer_id
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('bronze_tpch_customers')
                field: customer_id
      - name: order_status
        data_tests:
          - accepted_values:
              arguments:
                values: ['O', 'F', 'P']
      - name: total_price
        data_tests:
          - not_null

  - name: bronze_tpch_lineitem
    columns:
      - name: order_id
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('bronze_tpch_orders')
                field: order_id
      - name: quantity
        data_tests:
          - not_null
      - name: extended_price
        data_tests:
          - not_null

  - name: bronze_tpch_customers
    columns:
      - name: customer_id
        data_tests:
          - unique
          - not_null
      - name: market_segment
        data_tests:
          - accepted_values:
              arguments:
                values: ['AUTOMOBILE', 'BUILDING', 'FURNITURE', 'MACHINERY', 'HOUSEHOLD']

  - name: bronze_tpch_nations
    columns:
      - name: nation_id
        data_tests:
          - unique
          - not_null
      - name: nation_name
        data_tests:
          - unique
          - not_null